apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nextjs-replicaset
  labels:
    app: nextjs
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
      tier: frontend
  template:   
    metadata:
      name: nextjs-pod
      labels:   
        app: nextjs
        tier: frontend
    spec:
      containers:
        - name: nextjs-container
          image: lynakiddy/nextjs:latest
